import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Input, Spin } from "antd";
import { SearchOutlined } from "@ant-design/icons";
import Image from "next/image";
import Link from "next/link";
import Nav from "@/components/Nav";
import { databaseClient, DATABASE_ID, COLLECTIONS } from "@/appWrite-client/settings.config";

function Specialists() {
  const [disciplines, setDisciplines] = useState([]);
  const [filteredDisciplines, setFilteredDisciplines] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDisciplines();
  }, []);

  const loadDisciplines = async () => {
    try {
      const response = await databaseClient.listDocuments(
        DATABASE_ID,
        COLLECTIONS.DISCIPLINES
      );
      // Only show active AND public disciplines
      const publicDisciplines = response.documents.filter(
        d => d.status === 'active' && d.isPublic === true
      );
      setDisciplines(publicDisciplines);
      setFilteredDisciplines(publicDisciplines);
      setLoading(false);
    } catch (error) {
      console.error("Error loading disciplines:", error);
      setLoading(false);
    }
  };

  const onSearch = (e) => {
    const searchTerm = e.target.value.toLowerCase();
    const filterData = disciplines.filter((discipline) => {
      return (
        discipline.name.toLowerCase().includes(searchTerm) ||
        (discipline.description && discipline.description.toLowerCase().includes(searchTerm))
      );
    });
    setFilteredDisciplines(filterData);
  };

  const prefix = (
    <SearchOutlined
      onChange={(e) => onSearch(e)}
      style={{
        fontSize: 16,
        cursor: "pointer",
        marginRight: "5px",
      }}
    />
  );

  return (
    <>
      <Head>
        <title>Holistic Disciplines | AuraBUENA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-start justify-center w-screen">
        <div className="flex flex-col items-center justify-start h-screen gap-10 pt-5 pb-10 overflow-hidden scrollbar-hide xl:pt-24 xl:w-1/2">
          <Nav />

          <div className="w-full px-3 md:px-0">
            <h1 className="text-4xl text-center md:text-6xl text-[#2A9988]">
              Disciplines
            </h1>
          </div>
          <div className="flex flex-row items-center justify-center w-full py-6">
            <Input
              size="large"
              onChange={(e) => onSearch(e)}
              prefix={prefix}
              placeholder="Search for Providers"
              className="w-full px-4 text-lg border border-green-600 rounded-lg lg:w-2/3 md:w-2/3 sm:p-4 sm:px-4 searchDoc"
            />
          </div>
          <div className="w-full overflow-hidden scrollbar-hide">
            {loading ? (
              <div className="flex items-center justify-center h-64">
                <Spin size="large" />
              </div>
            ) : filteredDisciplines.length === 0 ? (
              <div className="flex items-center justify-center h-64">
                <p className="text-xl text-gray-500">No disciplines found</p>
              </div>
            ) : (
              <div className="grid h-full grid-cols-2 gap-4 pb-8 overflow-scroll scrollbar-hide dark:text-white md:grid-cols-3 lg:grid-cols-4 md:gap-6 lg:gap-8">
                {filteredDisciplines.map((discipline) => {
                  return (
                    <Link 
                      href={`/specialists/${discipline.slug || discipline.$id}`} 
                      key={discipline.$id}
                      className="hover:scale-105 transition-transform"
                    >
                      <div className="flex flex-col items-center justify-center p-4 bg-white rounded-lg shadow-md hover:shadow-lg">
                        <div className="relative w-20 h-20 mb-3 lg:w-24 lg:h-24">
                          {discipline.imageUrl ? (
                            <Image 
                              fill 
                              src={discipline.imageUrl} 
                              priority 
                              alt={discipline.name}
                              className="object-cover rounded-full"
                            />
                          ) : (
                            <div className="flex items-center justify-center w-full h-full bg-[#2A9988] rounded-full text-white text-2xl lg:text-3xl font-bold">
                              {discipline.name.charAt(0).toUpperCase()}
                            </div>
                          )}
                        </div>
                        <p className="text-sm font-medium text-center lg:text-base">{discipline.name}</p>
                        {discipline.description && (
                          <p className="mt-1 text-xs text-center text-gray-500 line-clamp-2">
                            {discipline.description}
                          </p>
                        )}
                      </div>
                    </Link>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}

export default Specialists;
