import React, { useMemo, useState } from "react";
import Nav from "@/components/Nav";
import Head from "next/head";
import Button from "@/components/UI/Button";
import AllHospitals from "@/components/Hospitals/allHospitals";
import NearbyHospitals from "@/components/Hospitals/nearbyHospitals";

export default function Hospitals({ allHospitals }) {
  const [all, setAll] = useState(true);
  const [nearby, setNearby] = useState(false);
  const [arrayUsed, setArrayUsed] = useState([]);

  const allNgHospitals = useMemo(
    () => <AllHospitals allHospitals={allHospitals} />,
    [allHospitals]
  );

  const nearbyNgHospitals = useMemo(() => <NearbyHospitals />, []);

  return (
    <>
      <Head>
        <title>Hospitals | NEXTGEN Clients</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen">
        <div className="flex mx-auto flex-col w-[95%] max-w-[900px] h-screen pt-5 pb-14 xl:pt-24 overflow-hidden scrollbar-hide">
          <Nav />

          <h1 className="text-4xl text-center md:text-6xl text-[#2A9988]">
            Hospitals
          </h1>

          <div className="flex flex-col h-full mt-10 overflow-hidden scrollbar-hide">
            <div className="flex items-center justify-around text-center dark:text-white">
              <Button
                cState={all}
                label={"All"}
                clickFunction={() => {
                  if (nearby == true) {
                    setNearby(false);
                  }
                  setAll(true);
                }}
              />

              <Button
                cState={nearby}
                label={"Nearby"}
                clickFunction={() => {
                  if (all == true) {
                    setAll(false);
                  }
                  setNearby(true);
                }}
              />
            </div>

            <div className="h-full">
              <div className="relative h-full pt-10 pb-8 overflow-hidden scrollbar-hide">
                {all ? allNgHospitals : nearbyNgHospitals}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const url =
    "https://overpass-api.de/api/interpreter?data=[out:json];area[name=%22Nigeria%22]-%3E.a;node(area.a)[%22amenity%22=%22hospital%22];out%20center;";

  try {
    const response = await fetch(url);
    
    // Check if the response is JSON
    const contentType = response.headers.get("content-type");
    if (!contentType || !contentType.includes("application/json")) {
      console.warn("API did not return JSON, using empty array");
      return {
        props: {
          allHospitals: [],
        },
        revalidate: 3600, // Revalidate every hour
      };
    }

    const data = await response.json();

    const allHospitals = [];
    if (data.elements && Array.isArray(data.elements)) {
      data.elements.forEach((data) => {
        if (!data.tags["addr:full"]) {
          return;
        }
        allHospitals.push(data);
      });
    }

    return {
      props: {
        allHospitals,
      },
      revalidate: 3600, // Revalidate every hour
    };
  } catch (error) {
    console.error("Error fetching hospitals:", error);
    return {
      props: {
        allHospitals: [],
      },
      revalidate: 3600, // Revalidate every hour
    };
  }
}
